spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  application:
    name: post-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888