-- liquibase formatted sql
--changeset vishnu:change_0001

CREATE TABLE media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at BIGINT,
   updated_at BIGINT,
   created_by VARCHAR(255),
   updated_by VARCHAR(255),
   url VARCHAR(255),
   media_type VARCHAR(255),
   status VARCHAR(255),
   post_id BIGINT,
   CONSTRAINT pk_media PRIMARY KEY (id)
);

ALTER TABLE media ADD CONSTRAINT FK_MEDIA_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);